export type PresetType = 'location' | 'camera' | 'lighting' | 'style';

export type BuiltinPresetDefinition = {
  type: PresetType;
  key: string;
  label: string;
  prompt: string;
  negative?: string;
};

export const BUILTIN_PRESETS: BuiltinPresetDefinition[] = [
  // Location presets
  { type: 'location', key: '', label: 'Üres preset', prompt: '' },
  { type: 'location', key: 'urban-street', label: 'Urban Street', prompt: 'dense Budapest urban street, late 1990s to early 2000s, layered storefronts, period-correct signage and lived-in city texture' },
  { type: 'location', key: 'apartment', label: 'Apartment Interior', prompt: 'small Budapest apartment interior, late 1990s to early 2000s, practical furniture and period-accurate daily-life clutter' },
  { type: 'location', key: 'office', label: 'Office', prompt: 'functional Budapest office interior, late 1990s to early 2000s, grounded corporate realism with era-appropriate fixtures' },
  { type: 'location', key: 'warehouse', label: 'Warehouse', prompt: 'Budapest industrial warehouse, late 1990s to early 2000s, hard surfaces, ambient dust, and period-correct utility details' },
  { type: 'location', key: 'rooftop', label: 'Rooftop', prompt: 'Budapest city rooftop, late 1990s to early 2000s, skyline depth, wind exposure, and practical safety details' },
  { type: 'location', key: 'subway', label: 'Subway Station', prompt: 'Budapest underground metro station, late 1990s to early 2000s, repeating geometry, public-transport wear, era-accurate materials' },
  { type: 'location', key: 'forest', label: 'Forest', prompt: 'forest edge around Budapest, late 1990s to early 2000s, layered vegetation with realistic regional atmosphere' },
  { type: 'location', key: 'industrial-yard', label: 'Industrial Yard', prompt: 'Budapest industrial yard, late 1990s to early 2000s, rugged materials, heavy-equipment traces, and period utility clutter' },
  { type: 'location', key: 'night-highway', label: 'Night Highway', prompt: 'Budapest night highway corridor, late 1990s to early 2000s, practical road infrastructure and sodium-vapor style lighting' },
  { type: 'location', key: 'interrogation-room', label: 'Interrogation Room', prompt: 'minimal Budapest interrogation room, late 1990s to early 2000s, controlled lighting, sparse furniture, period institutional finish' },
  { type: 'location', key: 'budai', label: 'Budai Family Room', prompt: 'Budai upper-middle-class room, late 1990s to early 2000s, inherited grandmother-era furniture, heavy wood pieces, floral upholstery, framed family portraits, layered wallpaper, antique lamps, side tables, and a lived-in but elegant bourgeois domestic atmosphere' },
  { type: 'location', key: 'bevasarlokozpont', label: 'Budapest Mall Clothing Store (1999)', prompt: 'interior of a Budapest H&M-style clothing store, 1999 to early 2000s, mirror-heavy layout, mannequins throughout, realistic retail staging' },
  { type: 'location', key: 'vaulted-cellar-server-room', label: 'Vaulted Brick Cellar / Retro Server Room', prompt: 'vaulted brick cellar interior, underground bunker-like room, thick brick walls, cable bundles snaking across the walls, floor, and ceiling, monitors and machines lining the perimeter, old arcade gaming cabinets and retro amusement machines packed shoulder to shoulder, stacked crates and cluttered salvage piled high, central sofa and armchairs with a small coffee table, chaotic clutter everywhere, ominous satanic motifs and occult symbols, posters and old prints pinned across the walls, grimy industrial atmosphere with a lived-in, overloaded technology den feel' },
  { type: 'location', key: 'mcdonalds-east-eu-2000', label: 'McDonalds East Europe (Late 90s / 2000)', prompt: 'East-European McDonalds interior, late 1990s to early 2000s, tiled floors, plastic seating, bright menu lightboxes, tray-based fast-food setup, era-authentic branding and lived-in public atmosphere' },
  { type: 'location', key: 'limousine-rear-seat-pov', label: 'Tágas Fekete Limuzin / Hátsó Ülés (POV)', prompt: 'spacious long-wheelbase luxury limousine interior viewed from the rear passenger compartment, seated rear-cabin perspective, generous legroom and wide black leather rear bench seat, deep black leather upholstery with realistic creases and wear, dark premium interior trim, front cabin clearly visible beyond the rear seat, two separate large front seats, center console and dashboard ahead, steering wheel and windshield visible from the rear passenger position, rear-view mirror hanging centrally above the dashboard with several small air fresheners dangling from it at different lengths, restrained ambient cabin lighting, realistic enclosed-vehicle geometry, believable distances and sightlines from the rear seat, slightly worn early-2000s luxury-car atmosphere, no people or character identities built into the location baseline' },
  { type: 'location', key: 'land-rover-interior-pov', label: 'Old Land Rover Interior (POV)', prompt: 'inside a battered old Land Rover interior, POV from the cabin, torn upholstery, cracked dashboard, worn controls, dusty glass, exposed metal, off-road fatigue, cramped vehicle geometry' },
  { type: 'location', key: 'white-studio-sofa', label: 'White Studio / Large Sofa', prompt: 'bright white studio backdrop, clean minimalist composition, one oversized turn-of-the-century sofa as the only major furniture piece, scattered throw pillows and blankets on the floor, soft neutral palette, open negative space, polished modern calm' },
  { type: 'location', key: 'hotel-courtyard-pool-cocktail-bar', label: 'Hotel Courtyard / Pool / Cocktail Bar', prompt: 'hotel inner courtyard with swimming pool under summer sunshine, ending in a cocktail bar at the far end of the pool' },

  // Camera presets
  { type: 'camera', key: 'pov', label: 'POV (First Person / Human Eye)', prompt: 'true first-person subjective point of view from the character\'s own eye position, the camera is the viewer\'s head and eyes rather than an external camera, scene experienced from inside the character, natural human binocular perspective, realistic eye-level height and head position appropriate to the character and physical situation, normal human field of view around 90-100 degrees horizontal, rectilinear perspective with natural proportions, realistic perspective convergence, physically plausible near and far distances, subtle natural head movement only when appropriate, hands or forearms and occasionally knees, feet, or lower legs may enter the frame naturally when physically visible from the character\'s own position, no third-person body view, no visible head, face, torso, camera rig, helmet, or floating camera, no over-the-shoulder framing, no external observer viewpoint, no dramatic lens exaggeration, no fisheye, no barrel distortion, no ultra-wide stretching, no impossible vanishing lines, no forced cinematic framing; for seated or enclosed situations such as a car rear seat, preserve the exact spatial geometry of the environment and show what a real person could actually see from that seat, with anatomically plausible eye height, reach, occlusion, and field of view' },
  { type: 'camera', key: 'closeup', label: 'Close-up', prompt: 'cinematic close-up portrait, subject fills frame, razor focus on eyes and facial details, shallow depth of field, creamy bokeh, soft directional key light with subtle rim light, emotionally intense and painterly composition' },
  { type: 'camera', key: 'wide', label: 'Wide', prompt: 'cinematic wide establishing shot, strong environmental storytelling, balanced foreground-midground-background layering, dramatic perspective depth, atmospheric haze, controlled contrast lighting, filmic color grading and art-directed composition' },
  { type: 'camera', key: 'fisheye', label: 'Fisheye', prompt: 'stylized fisheye lens shot, dynamic curvature and exaggerated perspective, bold composition lines, energetic visual tension, controlled edge distortion (subject remains readable), high-impact cinematic framing with artistic intent' },
  { type: 'camera', key: 'handheld', label: 'Handheld (Cinematic Realism)', prompt: 'documentary-style handheld framing, slight natural camera sway, organic imperfections, cinematic realism, soft motion character without heavy blur' },
  { type: 'camera', key: 'dutch', label: 'Dutch Angle (Tension)', prompt: 'cinematic dutch angle shot, intentional tilted horizon for psychological tension, bold diagonal composition, dramatic contrast, stylized thriller-like visual energy' },
  { type: 'camera', key: 'birdseye', label: "Bird's-Eye (Top-Down)", prompt: "bird's-eye top-down shot, geometric composition from high altitude, strong shape language, scene choreography clearly visible, atmospheric cinematic depth" },
  { type: 'camera', key: 'overtheshoulder', label: 'Over-the-Shoulder (POV Drama)', prompt: 'over-the-shoulder cinematic framing, foreground shoulder silhouette for depth, subject focus in midground, narrative POV tension, filmic blocking and lighting continuity' },
  { type: 'camera', key: 'wormseye', label: "Worm's-Eye (Heroic Low Angle)", prompt: "worm's-eye ultra low-angle shot from near ground level, towering perspective, heroic scale, dramatic sky/background separation, powerful cinematic presence" },
  { type: 'camera', key: 'speedcam1999', label: 'Rendőrségi Traffipax 1999 (Éjszakai)', prompt: 'fixed roadside police speed camera framing from late 1990s Hungary, slightly elevated telephoto angle aimed at lane center, rigid tripod-like composition, night xenon flash exposure, practical evidence capture priorities over artistry, subject vehicle centered with readable plate zone, official enforcement-photo geometry' },
  { type: 'camera', key: 'security-cam', label: 'Security Camera (Fixed Surveillance)', prompt: 'fixed elevated security camera framing, institutional surveillance realism, static composition with practical wide coverage, flat perspective priority over cinematic dramatization, late-1990s public-space monitoring aesthetic, subject and pathways clearly readable' },
  { type: 'camera', key: 'telephoto-stakeout', label: 'Telephoto Stakeout (Long-Lens Surveillance)', prompt: 'long-lens telephoto stakeout framing from distant vantage point, compressed perspective, voyeuristic observational mood, narrow depth plane with soft far-background blur, subtle atmospheric shimmer, subject readable but emotionally distant' },
  { type: 'camera', key: 'cctv-distorted', label: 'CCTV Fisheye Distortion', prompt: 'CCTV fisheye surveillance framing with controlled barrel distortion, wide hemispherical field, archive-footage realism, mild signal-loss texture and practical timestamp aesthetic, environment remains readable despite lens curvature' },
  { type: 'camera', key: 'reflection-pov', label: 'Reflection POV (Mirror/Glass)', prompt: 'subjective reflection POV through mirror or glass surface, slight edge warping and layered reflections, psychological intimacy with voyeuristic tension, foreground reflective plane preserved while main subject remains identity-accurate' },
  { type: 'camera', key: 'macro-forensic', label: 'Macro Forensic Detail', prompt: 'extreme macro forensic detail framing, isolate tiny evidence-level textures with razor-sharp focus plane, dramatic depth falloff, investigative documentation mood, tactile material realism with disciplined composition' },
  { type: 'camera', key: 'pov-dashboard', label: 'Dashboard POV (In-Vehicle)', prompt: 'in-vehicle dashboard POV framing from driver-height perspective, windshield glare and practical reflections, analog late-1990s interior cues, forward road depth and motion context preserved, documentary driving-surveillance realism' },
  { type: 'camera', key: 'atm-lens', label: 'ATM Hidden Camera Lens', prompt: 'ultra-wide distorted ATM hidden camera perspective, harsh greenish fluorescent lighting, low-res CRT monitor aesthetic, extreme paranoid surveillance framing, uncomfortably close midriff/face cutoff, digital artifacting' },
  { type: 'camera', key: 'fpv-kamikaze', label: 'FPV Kamikaze Dive', prompt: 'aggressive FPV drone dive perspective, extreme motion blur on edges, violent dutch tilt, hyper-kinetic dynamic tension, split-second before impact framing, digital transmission glitching and signal degradation' },
  { type: 'camera', key: 'peephole-voyeur', label: 'Peephole Voyeur POV', prompt: 'distorted optical peephole POV, extreme circular barrel distortion, claustrophobic vignette framing, dirty glass texture, high-contrast grimy hallway lighting, paranoid psychological thriller aesthetic' },
  { type: 'camera', key: 'thermal-predator', label: 'FLIR Thermal Imaging', prompt: 'FLIR thermal imaging camera perspective, high-contrast heat signature mapping, monochromatic or false-color infrared spectrum, clinical military targeting aesthetic, dehumanizing voyeuristic distance' },
  { type: 'camera', key: 'vhs-glitch-90s', label: '1995 VHS Camcorder', prompt: 'home video camcorder aesthetic from 1995, severe chromatic aberration, RGB channel shift, tracking lines, blown-out highlights, analog tape degradation, subjective shaky-cam intimacy, raw underground vibe' },
  { type: 'camera', key: 'bodycam-raid', label: 'Tactical Bodycam Raid', prompt: 'chest-mounted tactical bodycam perspective, chaotic wide-angle framing, harsh tactical flashlight illumination piercing absolute darkness, visceral frantic movement, raw unpolished true-crime aesthetic, partial arm/weapon in foreground' },

  // Lighting presets
  { type: 'lighting', key: 'night-moving-city', label: 'Éjszakai Városi Fények / Mozgó Limuzin', prompt: 'night interior lighting inside a moving luxury limousine, outside is completely dark with only intermittent city light sources visible through the windows, passing streetlights, storefronts, traffic signals, illuminated buildings, headlights and taillights sweep across the cabin in changing bands, brief pools of amber, white, red, and cool urban light move across the black leather seats and passengers, reflections glide across side windows and glossy interior trim, fleeting shadows travel rhythmically across faces and upholstery as the car moves through the city, natural window reflections layered with the dark cabin, practical low-light exposure, soft interior falloff between passing light sources, physically plausible light direction changing according to the moving city environment, no static studio lighting, no artificial neon wash, no permanent colored fill light, cinematic but observational night realism' },

  // Style presets
  { type: 'style', key: 'gritty', label: 'Vállalhatatlan / Gritty Underground', prompt: 'Vállalhatatlan visual language: raw late-1990s to early-2000s underground Budapest atmosphere, subdued and slightly dirty color palette, deep but not crushed blacks, restrained saturation, analog film grain, subtle VHS texture, practical imperfect lighting, lived-in surfaces, documentary immediacy, cinematic noir undertone, tactile image texture, visual imperfection that feels physical rather than digital', negative: 'no glossy commercial polish, no candy colors, no pristine digital clarity, no futuristic cyberpunk look, no sterile studio finish' },
  { type: 'style', key: 'noir-bw', label: 'Fekete-fehér Noir', prompt: 'Vállalhatatlan noir language in monochrome: expressive black-and-white photography, deep charcoal shadows, hard practical light, restrained midtones, silver-rich film grain, damp streets and worn surfaces, subtle halation, smoke and atmosphere, observational underground realism with a late-night Budapest feeling', negative: 'no bright modern color palette, no glossy fashion photography, no clean digital sharpness, no cheerful high-key lighting' },
  { type: 'style', key: 'vhs-glitch', label: 'VHS / Tapes 1999', prompt: 'Vállalhatatlan analog-tape aesthetic: late-1990s VHS capture, low saturation color, dirty blacks, faded reds and greens, soft CCD-like or tape softness, subtle tracking errors, scanline texture, chromatic bleed, tape noise, timestamp-era imperfection, accidental framing, underground home-video realism with a noir mood underneath', negative: 'no pristine 4K sharpness, no exaggerated cyberpunk glitch storm, no neon rainbow colors, no modern UI overlays' },
  { type: 'style', key: 'neo-noir-neon', label: 'Low-Saturation Neon Noir', prompt: 'Vállalhatatlan nocturnal noir with restrained neon: nearly monochrome charcoal and dirty-blue base, sparse cyan or magenta practical light accents, wet asphalt reflections, controlled bloom, atmospheric darkness, subtle analog grain and VHS softness, cinematic tension without becoming cyberpunk spectacle', negative: 'no highly saturated neon, no futuristic city design, no glossy music-video finish, no clean digital blacks' },
  { type: 'style', key: 'dreamy-ethereal', label: 'Dreamy Analog', prompt: 'Vállalhatatlan dream-state: desaturated analog color photography, milky blacks, muted beige, grey, olive and dusty blue tones, soft diffusion through old glass, gentle halation, suspended dust, faint haze, imperfect exposure and film grain, dreamlike but grounded in physical reality, melancholic nocturnal atmosphere rather than fantasy gloss', negative: 'no candy pastel palette, no fairy-tale fantasy styling, no excessive glow, no polished beauty campaign look' },
  { type: 'style', key: 'graphic-novel', label: 'Underground Graphic Novel', prompt: 'Vállalhatatlan graphic-novel language: mostly monochrome or severely desaturated ink palette, heavy black shapes, rough halftone, dirty paper texture, coarse print grain, imperfect contour edges, photocopy-like tonal breakup, cinematic noir blocking and underground zine sensibility, character identity kept highly readable', negative: 'no colorful superhero comic palette, no glossy digital comic rendering, no smooth airbrush gradients, no sterile vector perfection' },
  { type: 'style', key: 'police-speed-photo', label: 'Police Speed Photo 1999', prompt: 'Vállalhatatlan forensic-documentary language through a late-1990s Hungarian police speed camera: low-saturation near-monochrome color, hard frontal xenon flash, weak dynamic range, soft focus, fine sensor noise, slight motion smear, subtle compression and interlacing traces, mundane roadside reality, bureaucratic evidence-photo composition, period-correct visual decay, restrained noir tension without cinematic glamour', negative: 'no colorful modern grading, no dramatic blockbuster lighting, no pristine high-resolution capture, no futuristic interfaces, no glossy bokeh' },
  { type: 'style', key: 'direct-flash-2000', label: 'Direct Flash 2000', prompt: 'Vállalhatatlan party-documentary language: early-2000s compact camera snapshot, hard direct on-camera flash, low-saturation consumer-film colors, dirty shadows, blunt exposure, slight red-eye risk, imperfect white balance, visible grain, candid framing, crowded underground nightlife energy, crude but authentic photographic immediacy, subtle noir undertone', negative: 'no fashion-editorial lighting, no beauty retouching, no cinematic rim light, no glossy nightlife campaign aesthetic, no hyper-saturated party colors' },
  { type: 'style', key: 'expired-consumer-film', label: 'Lejárt 35 mm Film', prompt: 'Vállalhatatlan expired-film language: aged consumer 35mm stock with muted colors, dirty greens, dusty reds, cool or slightly yellowed white balance drift, lifted blacks, gentle grain, restrained halation, inconsistent exposure, soft edges and imperfect lab development, melancholic analog realism with an underground documentary feeling', negative: 'no perfect modern color science, no Instagram-filter look, no heavy VHS scanlines, no artificial glitch overlays, no glossy cinematic polish' },
  { type: 'style', key: 'xerox-punk-zine', label: 'Xerox Underground Zine', prompt: 'Vállalhatatlan underground print language: black-and-white photocopy aesthetic, crushed blacks, blown highlights, coarse halftone, toner grain, paper fibers, dirty xerox shadows, imperfect registration, rough cut-and-paste energy, cheap duplicated-flyer feel, noir-inspired silhouettes and strong graphic readability', negative: 'no full-color magazine finish, no smooth digital gradients, no glossy print perfection, no clean vector edges, no polished editorial typography' },
  { type: 'style', key: 'minidv-2003', label: 'MiniDV 2003', prompt: 'Vállalhatatlan early-digital memory language: 2002-2004 MiniDV camcorder image character, low-saturation cool color, small-sensor softness, interlaced texture, limited dynamic range, clipped highlights, subtle digital sharpening halos, chroma noise, tape-era compression, candid home-video composition and detached documentary realism with a dark nocturnal undertone', negative: 'no cinematic 35mm emulation, no VHS tracking lines, no modern HDR, no razor-sharp smartphone detail, no glossy commercial video look' },
  { type: 'style', key: 'sodium-vapor-documentary', label: 'Nátriumlámpás Dokumentum', prompt: 'Vállalhatatlan night-documentary language: Budapest after midnight under old sodium-vapor streetlights, muted amber pools against cold blue-black shadows, low-saturation palette, high-ISO grain, damp asphalt reflections, underexposed surroundings, practical light only, subdued contrast, quiet observational tension and physical urban decay, cinematic noir restraint without glamour', negative: 'no neon cyberpunk palette, no saturated orange-teal blockbuster grading, no theatrical studio light, no excessive fog, no glossy commercial night photography' },
  { type: 'style', key: 'risograph-underground', label: 'Risograph Underground', prompt: 'Vállalhatatlan print-object language: limited two-to-three-color risograph palette built from dirty black, off-white and one muted accent color, visible halftone dots, slight ink misregistration, paper fibers, rough overprint, imperfect density, underground poster and flyer sensibility, noir composition, analog imperfection and tactile physicality while keeping the character unmistakably recognizable', negative: 'no bright pop-art colors, no clean vector perfection, no glossy 3D surfaces, no photoreal skin rendering, no sterile modern poster design' },

];

export function getBuiltinPreset(type: PresetType, key: string): BuiltinPresetDefinition | undefined {
  return BUILTIN_PRESETS.find((preset) => preset.type === type && preset.key === key);
}

export function getBuiltinPresets(type: PresetType): BuiltinPresetDefinition[] {
  return BUILTIN_PRESETS.filter((preset) => preset.type === type);
}
