export type PresetType = 'location' | 'camera' | 'style';

export type BuiltinPresetDefinition = {
  type: PresetType;
  key: string;
  label: string;
  prompt: string;
  negative?: string;
};

export const BUILTIN_PRESETS: BuiltinPresetDefinition[] = [
  // Location presets
  { type: 'location', key: '', label: 'Üres preset', prompt: '' },
  { type: 'location', key: 'urban-street', label: 'Urban Street', prompt: 'dense Budapest urban street, late 1990s to early 2000s, layered storefronts, period-correct signage and lived-in city texture' },
  { type: 'location', key: 'apartment', label: 'Apartment Interior', prompt: 'small Budapest apartment interior, late 1990s to early 2000s, practical furniture and period-accurate daily-life clutter' },
  { type: 'location', key: 'office', label: 'Office', prompt: 'functional Budapest office interior, late 1990s to early 2000s, grounded corporate realism with era-appropriate fixtures' },
  { type: 'location', key: 'warehouse', label: 'Warehouse', prompt: 'Budapest industrial warehouse, late 1990s to early 2000s, hard surfaces, ambient dust, and period-correct utility details' },
  { type: 'location', key: 'rooftop', label: 'Rooftop', prompt: 'Budapest city rooftop, late 1990s to early 2000s, skyline depth, wind exposure, and practical safety details' },
  { type: 'location', key: 'subway', label: 'Subway Station', prompt: 'Budapest underground metro station, late 1990s to early 2000s, repeating geometry, public-transport wear, era-accurate materials' },
  { type: 'location', key: 'forest', label: 'Forest', prompt: 'forest edge around Budapest, late 1990s to early 2000s, layered vegetation with realistic regional atmosphere' },
  { type: 'location', key: 'industrial-yard', label: 'Industrial Yard', prompt: 'Budapest industrial yard, late 1990s to early 2000s, rugged materials, heavy-equipment traces, and period utility clutter' },
  { type: 'location', key: 'night-highway', label: 'Night Highway', prompt: 'Budapest night highway corridor, late 1990s to early 2000s, practical road infrastructure and sodium-vapor style lighting' },
  { type: 'location', key: 'interrogation-room', label: 'Interrogation Room', prompt: 'minimal Budapest interrogation room, late 1990s to early 2000s, controlled lighting, sparse furniture, period institutional finish' },
  { type: 'location', key: 'budai', label: 'Budai Family Room', prompt: 'Budai upper-middle-class room, late 1990s to early 2000s, inherited grandmother-era furniture, heavy wood pieces, floral upholstery, framed family portraits, layered wallpaper, antique lamps, side tables, and a lived-in but elegant bourgeois domestic atmosphere' },
  { type: 'location', key: 'bevasarlokozpont', label: 'Budapest Mall Clothing Store (1999)', prompt: 'interior of a Budapest H&M-style clothing store, 1999 to early 2000s, mirror-heavy layout, mannequins throughout, realistic retail staging' },
  { type: 'location', key: 'vaulted-cellar-server-room', label: 'Vaulted Brick Cellar / Retro Server Room', prompt: 'vaulted brick cellar interior, underground bunker-like room, thick brick walls, cable bundles snaking across the walls, floor, and ceiling, monitors and machines lining the perimeter, old arcade gaming cabinets and retro amusement machines packed shoulder to shoulder, stacked crates and cluttered salvage piled high, central sofa and armchairs with a small coffee table, chaotic clutter everywhere, ominous satanic motifs and occult symbols, posters and old prints pinned across the walls, grimy industrial atmosphere with a lived-in, overloaded technology den feel' },
  { type: 'location', key: 'mcdonalds-east-eu-2000', label: 'McDonalds East Europe (Late 90s / 2000)', prompt: 'East-European McDonalds interior, late 1990s to early 2000s, tiled floors, plastic seating, bright menu lightboxes, tray-based fast-food setup, era-authentic branding and lived-in public atmosphere' },
  { type: 'location', key: 'limousine-rear-seat-pov', label: 'Tágas Fekete Limuzin / Hátsó Ülés (POV)', prompt: 'spacious long-wheelbase luxury limousine interior viewed from the rear passenger compartment, seated rear-cabin perspective, generous legroom and a wide black leather rear bench seat, deep black leather upholstery with realistic creases and wear, dark premium interior trim, front cabin clearly visible beyond the rear seat, two separate large front seats, center console and dashboard ahead, steering wheel and windshield visible from the rear passenger position, rear-view mirror hanging centrally above the dashboard with several small air fresheners dangling from it at different lengths, restrained cabin geometry and believable sightlines from the rear seat, slightly worn early-2000s luxury-car atmosphere, no people or character identities built into the location baseline' },
  { type: 'location', key: 'land-rover-interior-pov', label: 'Old Land Rover Interior (POV)', prompt: 'inside a battered old Land Rover interior, POV from the cabin, torn upholstery, cracked dashboard, worn controls, dusty glass, exposed metal, off-road fatigue, cramped vehicle geometry' },
  { type: 'location', key: 'white-studio-sofa', label: 'White Studio / Large Sofa', prompt: 'bright white studio backdrop, clean minimalist composition, one oversized turn-of-the-century sofa as the only major furniture piece, scattered throw pillows and blankets on the floor, soft neutral palette, open negative space, polished modern calm' },
  { type: 'location', key: 'hotel-courtyard-pool-cocktail-bar', label: 'Hotel Courtyard / Pool / Cocktail Bar', prompt: 'hotel inner courtyard with swimming pool under summer sunshine, ending in a cocktail bar at the far end of the pool' },

  // Camera presets. These control lens, viewpoint, framing, and optical perspective only.
  { type: 'camera', key: 'closeup', label: 'Közeli · Close-up', prompt: 'close-up framing, face and upper body fill most of the frame, camera close to subject, shallow perspective' },
  { type: 'camera', key: 'extreme-closeup', label: 'Extrém közeli · Extreme Close-up', prompt: 'extreme close-up framing, isolate a small area of the face or a key physical detail, camera extremely close to subject' },
  { type: 'camera', key: 'medium', label: 'Közép · Medium Shot', prompt: 'medium shot framing from approximately waist or mid-torso upward, natural subject scale and readable surrounding space' },
  { type: 'camera', key: 'medium-wide', label: 'Közép-tág · Medium Wide', prompt: 'medium-wide framing, full upper body and substantial environment visible, balanced subject-to-space relationship' },
  { type: 'camera', key: 'wide', label: 'Tág · Wide Shot', prompt: 'wide framing with substantial environment visible around the subject, clear foreground, middle ground, and background separation' },
  { type: 'camera', key: 'extreme-wide', label: 'Nagyon tág · Extreme Wide', prompt: 'extreme wide framing, subject occupies a relatively small portion of the frame, environment dominates the composition' },

  { type: 'camera', key: 'ultrawide-14mm', label: 'Objektív · 14mm Ultra Wide', prompt: '14mm ultra-wide lens perspective, expansive field of view, strong foreground scale exaggeration, controlled edge stretching' },
  { type: 'camera', key: 'wide-24mm', label: 'Objektív · 24mm Wide', prompt: '24mm wide-angle lens perspective, broad environmental field of view, noticeable spatial depth and foreground presence' },
  { type: 'camera', key: 'environmental-35mm', label: 'Objektív · 35mm Environmental', prompt: '35mm environmental lens perspective, natural but spatially rich rendering, subject remains integrated with surroundings' },
  { type: 'camera', key: 'normal-50mm', label: 'Objektív · 50mm Natural', prompt: '50mm normal-lens perspective, balanced spatial proportions, restrained perspective distortion, natural subject scale' },
  { type: 'camera', key: 'portrait-85mm', label: 'Objektív · 85mm Portrait', prompt: '85mm short-telephoto perspective, flattering facial proportions, tighter background compression, subject clearly isolated' },
  { type: 'camera', key: 'telephoto-135mm', label: 'Objektív · 135mm Telephoto', prompt: '135mm telephoto perspective, compressed depth, distant camera position, narrow field of view' },
  { type: 'camera', key: 'compressed-telephoto', label: 'Objektív · Erősen komprimált tele', prompt: 'long telephoto lens with strong perspective compression, flattened spatial layers, distant observational camera position' },
  { type: 'camera', key: 'macro', label: 'Objektív · Macro', prompt: 'macro lens perspective, extreme proximity to subject detail, very shallow focus plane, tiny-scale material and surface emphasis' },
  { type: 'camera', key: 'fisheye', label: 'Optika · Fisheye', prompt: 'fisheye lens perspective with pronounced barrel curvature and very wide field of view, controlled distortion with subject kept readable' },
  { type: 'camera', key: 'tilt-shift', label: 'Optika · Tilt-shift', prompt: 'tilt-shift lens perspective, selective focus plane across the scene, miniature-like depth behavior while preserving realistic subject proportions' },

  { type: 'camera', key: 'low-angle', label: 'Nézőpont · Alulról', prompt: 'low-angle viewpoint from below eye level, camera looking upward, subject gains vertical presence within the frame' },
  { type: 'camera', key: 'ground-level', label: 'Nézőpont · Talajszint', prompt: 'ground-level viewpoint, camera positioned almost at floor or street height, foreground surface strongly participates in perspective' },
  { type: 'camera', key: 'wormseye', label: 'Nézőpont · Extrém alulnézet', prompt: 'extreme worm’s-eye viewpoint from very close to the ground, camera aimed sharply upward, towering vertical perspective' },
  { type: 'camera', key: 'high-angle', label: 'Nézőpont · Felülről', prompt: 'high-angle viewpoint from clearly above eye level, camera looking downward, visible top planes and reduced subject dominance' },
  { type: 'camera', key: 'overhead', label: 'Nézőpont · Merőleges overhead', prompt: 'direct overhead viewpoint, camera positioned above the scene and aimed straight down, graphic spatial geometry and clearly readable arrangement' },
  { type: 'camera', key: 'ceiling-corner', label: 'Nézőpont · Mennyezeti sarok', prompt: 'camera placed high in a ceiling corner, diagonal room geometry visible, surveillance-like spatial overview without any surveillance styling' },
  { type: 'camera', key: 'dutch-angle', label: 'Nézőpont · Dutch angle', prompt: 'deliberate off-level camera roll, tilted horizon, strong diagonal framing while vertical structures remain recognizably spatial' },
  { type: 'camera', key: 'profile', label: 'Nézőpont · Tiszta profil', prompt: 'strict side-profile viewpoint, camera perpendicular to the subject’s sagittal plane, clean lateral silhouette and spatial separation' },
  { type: 'camera', key: 'three-quarter-profile', label: 'Nézőpont · Háromnegyed profil', prompt: 'three-quarter profile viewpoint, camera offset from the subject front axis, balanced facial depth and body orientation' },

  { type: 'camera', key: 'over-shoulder', label: 'Filmes · Over-the-Shoulder', prompt: 'over-the-shoulder viewpoint with a close foreground shoulder or head framing one edge, camera positioned behind one subject toward the focal subject' },
  { type: 'camera', key: 'pov', label: 'Szubjektív POV · Emberi szem', prompt: 'strict true first-person subjective POV from the character’s exact eye position; the camera is physically located where the character’s eyes are, never outside the character and never observing the character; in a seated rear-car scene, V is behind the two front-seat passengers and the frame shows only what V could physically see from that exact seat position, with the two men’s broad backs in the foreground and the cabin, windshield and city beyond; V’s face, head, torso and body must NOT be directly visible anywhere in the image and may appear ONLY as a natural reflection in the rear-view mirror; the rear-view mirror reflection must read as V seeing himself, not as a second camera angle; realistic human eye height, natural 90-100 degree horizontal field of view, rectilinear perspective, physically plausible occlusion, reach and spatial geometry; hands or knees may appear only when naturally visible from V’s own seated position; absolutely no third-person shot, no external observer, no over-the-shoulder shot, no visible V outside the mirror, no floating camera, no camera rig, no head-mounted-camera depiction, no impossible body placement, no fisheye, no barrel distortion, no ultra-wide stretching, no impossible vanishing lines' },
  { type: 'camera', key: 'subjective-pov', label: 'Filmes · Szubjektív POV', prompt: 'first-person subjective viewpoint from the character’s visual position, camera height and orientation aligned with the character’s line of sight' },
  { type: 'camera', key: 'rear-three-quarter', label: 'Filmes · Hátulról 3/4', prompt: 'rear three-quarter viewpoint from behind the subject, camera offset to reveal both silhouette and spatial destination' },
  { type: 'camera', key: 'foreground-obstructed', label: 'Filmes · Előtérrel kitakart', prompt: 'camera peers past a strong foreground obstruction such as a doorway edge, curtain, object, foliage, or furniture, creating layered depth without changing the scene style' },
  { type: 'camera', key: 'doorway-peek', label: 'Filmes · Ajtófélfán túlról', prompt: 'camera positioned just beyond a doorway or opening, subject partially framed by the architectural edge, layered foreground and midground depth' },
  { type: 'camera', key: 'through-glass', label: 'Filmes · Üvegen keresztül', prompt: 'camera positioned behind a glass surface, subject viewed through the transparent plane with subtle refraction and foreground depth' },
  { type: 'camera', key: 'reflection', label: 'Filmes · Tükör / tükröződés', prompt: 'camera uses a reflective surface as the primary viewpoint, subject composed through a mirror or reflective plane while preserving spatial orientation' },
  { type: 'camera', key: 'dashboard-pov', label: 'Filmes · Műszerfal POV', prompt: 'camera positioned inside a vehicle near dashboard height, forward or sideward cabin perspective, windshield frame and interior geometry can define the foreground' },

  { type: 'camera', key: 'corner-wide', label: 'Kompozíció · Sarokból tág', prompt: 'wide lens from a room or street corner, strong converging lines, deep diagonal space, subject placed within the geometry rather than centered by default' },
  { type: 'camera', key: 'centered-symmetry', label: 'Kompozíció · Középtengely', prompt: 'camera aligned precisely with the central axis of the environment, strong bilateral or architectural symmetry, subject placed on the primary axis' },
  { type: 'camera', key: 'off-axis', label: 'Kompozíció · Tengelyen kívül', prompt: 'camera deliberately offset from the dominant spatial axis, asymmetrical perspective, subject placed away from the geometric center while remaining readable' },
  { type: 'camera', key: 'long-corridor', label: 'Kompozíció · Hosszú perspektíva', prompt: 'camera aligned down a long corridor, road, tunnel, or narrow spatial axis, emphasizing converging lines and deep vanishing-point perspective' },
  { type: 'camera', key: 'surrounding-subject', label: 'Kompozíció · Körbezáró tér', prompt: 'camera placed within close surrounding geometry such as walls, furniture, vehicles, or structural elements, creating an immersive enclosed frame' },
  // Style presets
  { type: 'style', key: 'gritty', label: 'Vállalhatatlan / Gritty Underground', prompt: 'Vállalhatatlan visual language: raw late-1990s to early-2000s underground Budapest atmosphere, subdued and slightly dirty color palette, deep but not crushed blacks, restrained saturation, analog film grain, subtle VHS texture, practical imperfect lighting, lived-in surfaces, documentary immediacy, cinematic noir undertone, tactile image texture, visual imperfection that feels physical rather than digital', negative: 'no glossy commercial polish, no candy colors, no pristine digital clarity, no futuristic cyberpunk look, no sterile studio finish' },
  { type: 'style', key: 'noir-bw', label: 'Fekete-fehér Noir', prompt: 'Vállalhatatlan noir language in monochrome: expressive black-and-white photography, deep charcoal shadows, hard practical light, restrained midtones, silver-rich film grain, damp streets and worn surfaces, subtle halation, smoke and atmosphere, observational underground realism with a late-night Budapest feeling', negative: 'no bright modern color palette, no glossy fashion photography, no clean digital sharpness, no cheerful high-key lighting' },
  { type: 'style', key: 'vhs-glitch', label: 'VHS / Tapes 1999', prompt: 'Vállalhatatlan analog-tape aesthetic: late-1990s VHS capture, low saturation color, dirty blacks, faded reds and greens, soft CCD-like or tape softness, subtle tracking errors, scanline texture, chromatic bleed, tape noise, timestamp-era imperfection, accidental framing, underground home-video realism with a noir mood underneath', negative: 'no pristine 4K sharpness, no exaggerated cyberpunk glitch storm, no neon rainbow colors, no modern UI overlays' },
  { type: 'style', key: 'neo-noir-neon', label: 'Low-Saturation Neon Noir', prompt: 'Vállalhatatlan nocturnal noir with restrained neon: nearly monochrome charcoal and dirty-blue base, sparse cyan or magenta practical light accents, wet asphalt reflections, controlled bloom, atmospheric darkness, subtle analog grain and VHS softness, cinematic tension without becoming cyberpunk spectacle', negative: 'no highly saturated neon, no futuristic city design, no glossy music-video finish, no clean digital blacks' },
  { type: 'style', key: 'dreamy-ethereal', label: 'Dreamy Analog', prompt: 'Vállalhatatlan dream-state: desaturated analog color photography, milky blacks, muted beige, grey, olive and dusty blue tones, soft diffusion through old glass, gentle halation, suspended dust, faint haze, imperfect exposure and film grain, dreamlike but grounded in physical reality, melancholic nocturnal atmosphere rather than fantasy gloss', negative: 'no candy pastel palette, no fairy-tale fantasy styling, no excessive glow, no polished beauty campaign look' },
  { type: 'style', key: 'graphic-novel', label: 'Underground Graphic Novel', prompt: 'Vállalhatatlan graphic-novel language: mostly monochrome or severely desaturated ink palette, heavy black shapes, rough halftone, dirty paper texture, coarse print grain, imperfect contour edges, photocopy-like tonal breakup, cinematic noir blocking and underground zine sensibility, character identity kept highly readable', negative: 'no colorful superhero comic palette, no glossy digital comic rendering, no smooth airbrush gradients, no sterile vector perfection' },
  { type: 'style', key: 'police-speed-photo', label: 'Police Speed Photo 1999', prompt: 'Vállalhatatlan forensic-documentary language through a late-1990s Hungarian police speed camera: low-saturation near-monochrome color, hard frontal xenon flash, weak dynamic range, soft focus, fine sensor noise, slight motion smear, subtle compression and interlacing traces, mundane roadside reality, bureaucratic evidence-photo composition, period-correct visual decay, restrained noir tension without cinematic glamour', negative: 'no colorful modern grading, no dramatic blockbuster lighting, no pristine high-resolution capture, no futuristic interfaces, no glossy bokeh' },
  { type: 'style', key: 'direct-flash-2000', label: 'Direct Flash 2000', prompt: 'Vállalhatatlan party-documentary language: early-2000s compact camera snapshot, hard direct on-camera flash, low-saturation consumer-film colors, dirty shadows, blunt exposure, slight red-eye risk, imperfect white balance, visible grain, candid framing, crowded underground nightlife energy, crude but authentic photographic immediacy, subtle noir undertone', negative: 'no fashion-editorial lighting, no beauty retouching, no cinematic rim light, no glossy nightlife campaign aesthetic, no hyper-saturated party colors' },
  { type: 'style', key: 'expired-consumer-film', label: 'Lejárt 35 mm Film', prompt: 'Vállalhatatlan expired-film language: aged consumer 35mm stock with muted colors, dirty greens, dusty reds, cool or slightly yellowed white balance drift, lifted blacks, gentle grain, restrained halation, inconsistent exposure, soft edges and imperfect lab development, melancholic analog realism with an underground documentary feeling', negative: 'no perfect modern color science, no Instagram-filter look, no heavy VHS scanlines, no artificial glitch overlays, no glossy cinematic polish' },
  { type: 'style', key: 'xerox-punk-zine', label: 'Xerox Underground Zine', prompt: 'Vállalhatatlan underground print language: black-and-white photocopy aesthetic, crushed blacks, blown highlights, coarse halftone, toner grain, paper fibers, dirty xerox shadows, imperfect registration, rough cut-and-paste energy, cheap duplicated-flyer feel, noir-inspired silhouettes and strong graphic readability', negative: 'no full-color magazine finish, no smooth digital gradients, no glossy print perfection, no clean vector edges, no polished editorial typography' },
  { type: 'style', key: 'minidv-2003', label: 'MiniDV 2003', prompt: 'Vállalhatatlan early-digital memory language: 2002-2004 MiniDV camcorder image character, low-saturation cool color, small-sensor softness, interlaced texture, limited dynamic range, clipped highlights, subtle digital sharpening halos, chroma noise, tape-era compression, candid home-video composition and detached documentary realism with a dark nocturnal undertone', negative: 'no cinematic 35mm emulation, no VHS tracking lines, no modern HDR, no razor-sharp smartphone detail, no glossy commercial video look' },
  { type: 'style', key: 'sodium-vapor-documentary', label: 'Nátriumlámpás Dokumentum', prompt: 'Vállalhatatlan night-documentary language: Budapest after midnight under old sodium-vapor streetlights, muted amber pools against cold blue-black shadows, low-saturation palette, high-ISO grain, damp asphalt reflections, underexposed surroundings, practical light only, subdued contrast, quiet observational tension and physical urban decay, cinematic noir restraint without glamour', negative: 'no neon cyberpunk palette, no saturated orange-teal blockbuster grading, no theatrical studio light, no excessive fog, no glossy commercial night photography' },
  { type: 'style', key: 'risograph-underground', label: 'Risograph Underground', prompt: 'Vállalhatatlan print-object language: limited two-to-three-color risograph palette built from dirty black, off-white and one muted accent color, visible halftone dots, slight ink misregistration, paper fibers, rough overprint, imperfect density, underground poster and flyer sensibility, noir composition, analog imperfection and tactile physicality while keeping the character unmistakably recognizable', negative: 'no bright pop-art colors, no clean vector perfection, no glossy 3D surfaces, no photoreal skin rendering, no sterile modern poster design' },

];

export function getBuiltinPreset(type: PresetType, key: string): BuiltinPresetDefinition | undefined {
  return BUILTIN_PRESETS.find((preset) => preset.type === type && preset.key === key);
}

export function getBuiltinPresets(type: PresetType): BuiltinPresetDefinition[] {
  return BUILTIN_PRESETS.filter((preset) => preset.type === type);
}
