export type PresetType = 'location' | 'camera' | 'style';

export type BuiltinPresetDefinition = {
  type: PresetType;
  key: string;
  label: string;
  prompt: string;
  negative?: string;
};

export const BUILTIN_PRESETS: BuiltinPresetDefinition[] = [
  // Location presets
  { type: 'location', key: '', label: 'Üres preset', prompt: '' },
  { type: 'location', key: 'urban-street', label: 'Urban Street', prompt: 'dense Budapest urban street, late 1990s to early 2000s, layered storefronts, period-correct signage and lived-in city texture' },
  { type: 'location', key: 'apartment', label: 'Apartment Interior', prompt: 'small Budapest apartment interior, late 1990s to early 2000s, practical furniture and period-accurate daily-life clutter' },
  { type: 'location', key: 'office', label: 'Office', prompt: 'functional Budapest office interior, late 1990s to early 2000s, grounded corporate realism with era-appropriate fixtures' },
  { type: 'location', key: 'warehouse', label: 'Warehouse', prompt: 'Budapest industrial warehouse, late 1990s to early 2000s, hard surfaces, ambient dust, and period-correct utility details' },
  { type: 'location', key: 'rooftop', label: 'Rooftop', prompt: 'Budapest city rooftop, late 1990s to early 2000s, skyline depth, wind exposure, and practical safety details' },
  { type: 'location', key: 'subway', label: 'Subway Station', prompt: 'Budapest underground metro station, late 1990s to early 2000s, repeating geometry, public-transport wear, era-accurate materials' },
  { type: 'location', key: 'forest', label: 'Forest', prompt: 'forest edge around Budapest, late 1990s to early 2000s, layered vegetation with realistic regional atmosphere' },
  { type: 'location', key: 'industrial-yard', label: 'Industrial Yard', prompt: 'Budapest industrial yard, late 1990s to early 2000s, rugged materials, heavy-equipment traces, and period utility clutter' },
  { type: 'location', key: 'night-highway', label: 'Night Highway', prompt: 'Budapest night highway corridor, late 1990s to early 2000s, practical road infrastructure and sodium-vapor style lighting' },
  { type: 'location', key: 'interrogation-room', label: 'Interrogation Room', prompt: 'minimal Budapest interrogation room, late 1990s to early 2000s, controlled lighting, sparse furniture, period institutional finish' },
  { type: 'location', key: 'budai', label: 'Budai Family Room', prompt: 'Budai upper-middle-class room, late 1990s to early 2000s, inherited grandmother-era furniture, heavy wood pieces, floral upholstery, framed family portraits, layered wallpaper, antique lamps, side tables, and a lived-in but elegant bourgeois domestic atmosphere' },
  { type: 'location', key: 'bevasarlokozpont', label: 'Budapest Mall Clothing Store (1999)', prompt: 'interior of a Budapest H&M-style clothing store, 1999 to early 2000s, mirror-heavy layout, mannequins throughout, realistic retail staging' },
  { type: 'location', key: 'vaulted-cellar-server-room', label: 'Vaulted Brick Cellar / Retro Server Room', prompt: 'vaulted brick cellar interior, underground bunker-like room, thick brick walls, cable bundles snaking across the walls, floor, and ceiling, monitors and machines lining the perimeter, old arcade gaming cabinets and retro amusement machines packed shoulder to shoulder, stacked crates and cluttered salvage piled high, central sofa and armchairs with a small coffee table, chaotic clutter everywhere, ominous satanic motifs and occult symbols, posters and old prints pinned across the walls, grimy industrial atmosphere with a lived-in, overloaded technology den feel' },
  { type: 'location', key: 'mcdonalds-east-eu-2000', label: 'McDonalds East Europe (Late 90s / 2000)', prompt: 'East-European McDonalds interior, late 1990s to early 2000s, tiled floors, plastic seating, bright menu lightboxes, tray-based fast-food setup, era-authentic branding and lived-in public atmosphere' },
  { type: 'location', key: 'land-rover-interior-pov', label: 'Old Land Rover Interior (POV)', prompt: 'inside a battered old Land Rover interior, POV from the cabin, torn upholstery, cracked dashboard, worn controls, dusty glass, exposed metal, off-road fatigue, cramped vehicle geometry' },
  { type: 'location', key: 'white-studio-sofa', label: 'White Studio / Large Sofa', prompt: 'bright white studio backdrop, clean minimalist composition, one oversized turn-of-the-century sofa as the only major furniture piece, scattered throw pillows and blankets on the floor, soft neutral palette, open negative space, polished modern calm' },
  { type: 'location', key: 'hotel-courtyard-pool-cocktail-bar', label: 'Hotel Courtyard / Pool / Cocktail Bar', prompt: 'hotel inner courtyard with swimming pool under summer sunshine, ending in a cocktail bar at the far end of the pool' },

  // Camera presets
  { type: 'camera', key: 'closeup', label: 'Close-up', prompt: 'cinematic close-up portrait, subject fills frame, razor focus on eyes and facial details, shallow depth of field, creamy bokeh, soft directional key light with subtle rim light, emotionally intense and painterly composition' },
  { type: 'camera', key: 'wide', label: 'Wide', prompt: 'cinematic wide establishing shot, strong environmental storytelling, balanced foreground-midground-background layering, dramatic perspective depth, atmospheric haze, controlled contrast lighting, filmic color grading and art-directed composition' },
  { type: 'camera', key: 'fisheye', label: 'Fisheye', prompt: 'stylized fisheye lens shot, dynamic curvature and exaggerated perspective, bold composition lines, energetic visual tension, controlled edge distortion (subject remains readable), high-impact cinematic framing with artistic intent' },
  { type: 'camera', key: 'handheld', label: 'Handheld (Cinematic Realism)', prompt: 'documentary-style handheld framing, slight natural camera sway, organic imperfections, cinematic realism, soft motion character without heavy blur' },
  { type: 'camera', key: 'dutch', label: 'Dutch Angle (Tension)', prompt: 'cinematic dutch angle shot, intentional tilted horizon for psychological tension, bold diagonal composition, dramatic contrast, stylized thriller-like visual energy' },
  { type: 'camera', key: 'birdseye', label: "Bird's-Eye (Top-Down)", prompt: "bird's-eye top-down shot, geometric composition from high altitude, strong shape language, scene choreography clearly visible, atmospheric cinematic depth" },
  { type: 'camera', key: 'overtheshoulder', label: 'Over-the-Shoulder (POV Drama)', prompt: 'over-the-shoulder cinematic framing, foreground shoulder silhouette for depth, subject focus in midground, narrative POV tension, filmic blocking and lighting continuity' },
  { type: 'camera', key: 'wormseye', label: "Worm's-Eye (Heroic Low Angle)", prompt: "worm's-eye ultra low-angle shot from near ground level, towering perspective, heroic scale, dramatic sky/background separation, powerful cinematic presence" },
  { type: 'camera', key: 'speedcam1999', label: 'Rendőrségi Traffipax 1999 (Éjszakai)', prompt: 'fixed roadside police speed camera framing from late 1990s Hungary, slightly elevated telephoto angle aimed at lane center, rigid tripod-like composition, night xenon flash exposure, practical evidence capture priorities over artistry, subject vehicle centered with readable plate zone, official enforcement-photo geometry' },
  { type: 'camera', key: 'security-cam', label: 'Security Camera (Fixed Surveillance)', prompt: 'fixed elevated security camera framing, institutional surveillance realism, static composition with practical wide coverage, flat perspective priority over cinematic dramatization, late-1990s public-space monitoring aesthetic, subject and pathways clearly readable' },
  { type: 'camera', key: 'telephoto-stakeout', label: 'Telephoto Stakeout (Long-Lens Surveillance)', prompt: 'long-lens telephoto stakeout framing from distant vantage point, compressed perspective, voyeuristic observational mood, narrow depth plane with soft far-background blur, subtle atmospheric shimmer, subject readable but emotionally distant' },
  { type: 'camera', key: 'cctv-distorted', label: 'CCTV Fisheye Distortion', prompt: 'CCTV fisheye surveillance framing with controlled barrel distortion, wide hemispherical field, archive-footage realism, mild signal-loss texture and practical timestamp aesthetic, environment remains readable despite lens curvature' },
  { type: 'camera', key: 'reflection-pov', label: 'Reflection POV (Mirror/Glass)', prompt: 'subjective reflection POV through mirror or glass surface, slight edge warping and layered reflections, psychological intimacy with voyeuristic tension, foreground reflective plane preserved while main subject remains identity-accurate' },
  { type: 'camera', key: 'macro-forensic', label: 'Macro Forensic Detail', prompt: 'extreme macro forensic detail framing, isolate tiny evidence-level textures with razor-sharp focus plane, dramatic depth falloff, investigative documentation mood, tactile material realism with disciplined composition' },
  { type: 'camera', key: 'pov-dashboard', label: 'Dashboard POV (In-Vehicle)', prompt: 'in-vehicle dashboard POV framing from driver-height perspective, windshield glare and practical reflections, analog late-1990s interior cues, forward road depth and motion context preserved, documentary driving-surveillance realism' },
  { type: 'camera', key: 'atm-lens', label: 'ATM Hidden Camera Lens', prompt: 'ultra-wide distorted ATM hidden camera perspective, harsh greenish fluorescent lighting, low-res CRT monitor aesthetic, extreme paranoid surveillance framing, uncomfortably close midriff/face cutoff, digital artifacting' },
  { type: 'camera', key: 'fpv-kamikaze', label: 'FPV Kamikaze Dive', prompt: 'aggressive FPV drone dive perspective, extreme motion blur on edges, violent dutch tilt, hyper-kinetic dynamic tension, split-second before impact framing, digital transmission glitching and signal degradation' },
  { type: 'camera', key: 'peephole-voyeur', label: 'Peephole Voyeur POV', prompt: 'distorted optical peephole POV, extreme circular barrel distortion, claustrophobic vignette framing, dirty glass texture, high-contrast grimy hallway lighting, paranoid psychological thriller aesthetic' },
  { type: 'camera', key: 'thermal-predator', label: 'FLIR Thermal Imaging', prompt: 'FLIR thermal imaging camera perspective, high-contrast heat signature mapping, monochromatic or false-color infrared spectrum, clinical military targeting aesthetic, dehumanizing voyeuristic distance' },
  { type: 'camera', key: 'vhs-glitch-90s', label: '1995 VHS Camcorder', prompt: 'home video camcorder aesthetic from 1995, severe chromatic aberration, RGB channel shift, tracking lines, blown-out highlights, analog tape degradation, subjective shaky-cam intimacy, raw underground vibe' },
  { type: 'camera', key: 'bodycam-raid', label: 'Tactical Bodycam Raid', prompt: 'chest-mounted tactical bodycam perspective, chaotic wide-angle framing, harsh tactical flashlight illumination piercing absolute darkness, visceral frantic movement, raw unpolished true-crime aesthetic, partial arm/weapon in foreground' },

  // Style presets
  { type: 'style', key: 'gritty', label: 'Gritty Underground (Default)', prompt: 'gritty underground aesthetic, analog film grain, high contrast, dirty textures, cinematic lighting, slight VHS noise, not clean, not polished' },
  { type: 'style', key: 'noir-bw', label: 'Black and White Film Noir', prompt: 'black and white film noir look, deep shadows and hard key light, strong chiaroscuro contrast, moody smoke and atmospheric depth, wet streets and reflective highlights, vintage 1940s cinema tone', negative: 'no full color palette, no bright candy colors' },
  { type: 'style', key: 'vhs-glitch', label: 'Glitch VHS Analog Camera', prompt: 'retro VHS analog camera aesthetic, tracking lines and slight signal interference, chromatic aberration and color bleed, timecode-like tape capture vibe, soft analog blur and scanline texture, occasional digital glitch accents', negative: 'no pristine digital sharpness, no clean modern DSLR look' },
  { type: 'style', key: 'neo-noir-neon', label: 'Neo Noir Neon', prompt: 'neo noir cinematic style, neon practical lights in cyan and magenta accents, deep blacks with controlled bloom, rainy night reflections and urban mood, stylized high contrast with modern filmic grading' },
  { type: 'style', key: 'dreamy-ethereal', label: 'Dreamy Ethereal', prompt: 'dreamy ethereal atmosphere, soft diffusion and gentle bloom, pastel-tinted cinematic palette, mist, dust motes and floating ambient particles, poetic composition with delicate light transitions' },
  { type: 'style', key: 'graphic-novel', label: 'Graphic Novel', prompt: 'graphic novel illustration style, ink-like contour emphasis, bold silhouette readability, posterized contrast and stylized shading, panel-ready dramatic composition', negative: 'no photoreal skin microdetail, no smooth airbrushed realism' },
  { type: 'style', key: 'police-speed-photo', label: 'Police Speeding Camera Photo', prompt: 'roadside Hungarian police speed enforcement camera photo aesthetic, captured in 1999, telephoto compression with long-lens perspective and slight framing misalignment, night-time xenon flash burst with hard frontal illumination and deep background falloff, intentionally degraded late-1990s capture quality: low resolution, visible compression artifacts, interlacing traces, high sensor noise, soft focus and slight motion smear typical of old enforcement hardware, forensic documentary realism with neutral-cool color grading and weak dynamic range, official radar HUD overlay in Hungarian with blocky monochrome text: "SEBESSÉG", "MÉRT", "SÁV", "CÉLPONT", embedded Hungarian evidence metadata strip: "DÁTUM: 1999.11.xx", "IDŐ", "HELYSZÍN", "MÉRŐESZKÖZ", roadside context with lane markings and traffic signage, practical non-cinematic composition', negative: 'no artistic bokeh glamour look, no stylized neon color grading, no cinematic depth-of-field hero framing, no modern smartphone UI elements, no modern high-resolution sharpness, no english UI labels in overlay' },
];

export function getBuiltinPreset(type: PresetType, key: string): BuiltinPresetDefinition | undefined {
  return BUILTIN_PRESETS.find((preset) => preset.type === type && preset.key === key);
}

export function getBuiltinPresets(type: PresetType): BuiltinPresetDefinition[] {
  return BUILTIN_PRESETS.filter((preset) => preset.type === type);
}
